### ISSUE TITLE
Release 1.0 is really old - make a new release

### ISSUE THREAD

**Issue by urjitbhatia** [jbrukh/bayesian#25]
1.0 is still importing things like "gob" instead of "encoding/gob" etc. Can you make a new release? I can also help co-maintain the project is that helps.

Tools like `dep` will pick up release versions for most people and they will get code that won't work for newer versions of go.

Thanks!

**Comment by kisPocok** [comment]
Until we got the version, you can use master branch for `dep`.

```
[[constraint]]
  name = "github.com/jbrukh/bayesian"
  branch = "master"
```

**Comment by jbrukh** [comment]
Hey sorry for the egregious slowness. As you can tell, this project hasn't been my focus. :D

@urjitbhatia @kisPocok If you guys are up for maintaining, I'm happy to add you as collaborators. Let me know.

**Comment by kisPocok** [comment]
My IP150 got fire (really) so I choose another mainboard for the next time. So, this is a small "No" for your question :)

**Comment by urjitbhatia** [comment]
@jbrukh thanks, I am happy to help with this project!

**Comment by jbrukh** [comment]
@urjitbhatia Thanks for your interest! You are now a collaborator for this repo. I am happy to look at PRs.
