### ISSUE TITLE
Panic if underflow is detected in `SafeProbScores`

### ISSUE THREAD

**Issue by yml** [jbrukh/bayesian#7]
> SafeProbScores ... If an underflow is detected, this method panics

[Source](https://github.com/jbrukh/bayesian/blob/master/bayesian.go#L322-L323)

I am getting a bit confused by the comment in the method above according to the doc this method is suppose to `panic` but the code instead returns an [error](https://github.com/jbrukh/bayesian/blob/master/bayesian.go#L359-L364).

Am I missing something ?

**Comment by tritonresearch** [comment]
Your confusion is not unwarranted -- the comment is incorrect. In the case of underflow, the method will return an error. The comment still applies if you replace "returns an error" for "panics".

Will fix.

**Comment by jbrukh** [comment]
Your confusion is not unwarranted -- the comment is incorrect. In the case of underflow, the method will return an error. The comment still applies if you replace "returns an error" for "panics".

Will fix.

**Comment by yml** [comment]
Waouuu that was fast :-) Thank you very much for releasing this code and accepting PR.

**Comment by jbrukh** [comment]
My pleasure. Thanks for contributing.
